# -*- coding: utf-8 -*-
"""Self-Supervised Stroke Severity Assessment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118Kr2SiIcA17Qevr2pIioCHbobVwWZzf
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# torch>=2.0.0
# torchvision>=0.15.0
# monai>=1.2.0
# numpy>=1.24.0
# matplotlib>=3.7.0
# seaborn>=0.12.0
# tqdm>=4.65.0
# scikit-learn>=1.3.0
# pandas>=2.0.0
# pillow>=9.5.0

pip install -r requirements.txt

# ============================================================
# COMPLETE RUNNABLE CODE FOR JUPYTER NOTEBOOK (FIXED)
# Self-Supervised Stroke Severity Assessment with EWC + Replay
# Target: Prof. Kavitha (Nagasaki University)
# Includes Fisher Information Heatmap
# ============================================================

import os
import random
import pickle
import torch
import torch.nn as nn
import torchvision.models as models
import numpy as np
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
from collections import deque
from sklearn.metrics import accuracy_score, f1_score
import matplotlib.pyplot as plt
import seaborn as sns

# ------------------------- CONFIG -------------------------
class Config:
    data_root = "./data/isles2022"
    img_size = (128, 128)
    num_classes = 2
    batch_size = 32
    epochs_per_task = 2          # Reduced for quick testing (change to 20 later)
    lr = 1e-3
    weight_decay = 1e-4
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    seed = 42
    ewc_lambda = 5000
    fisher_sample_size = 200
    buffer_capacity = 200
    replay_batch_size = 32
    log_interval = 10
    plot_dir = "./plots"
    model_dir = "./checkpoints"

# ------------------------- UTILS -------------------------
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def compute_metrics(preds, labels):
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average='binary', zero_division=0)
    return acc, f1

def save_checkpoint(model, optimizer, epoch, filename):
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict() if optimizer else None,
    }, filename)

# ------------------------- DATASET (Simulated) with channel fix -------------------------
class StrokeDataset(Dataset):
    """Simulated stroke dataset – returns 3-channel images (RGB) by repeating grayscale."""
    def __init__(self, synthetic=True, length=500, img_size=(128,128)):
        self.length = length
        self.img_size = img_size
        self.synthetic = synthetic

    def __len__(self):
        return self.length

    def __getitem__(self, idx):
        if self.synthetic:
            img = np.random.randn(1, *self.img_size).astype(np.float32)  # (1,128,128)
            label = 1 if np.random.rand() > 0.5 else 0
        else:
            img = np.random.randn(1, *self.img_size).astype(np.float32) * 0.8 + 0.2
            label = 1 if np.random.rand() > 0.4 else 0
        # Convert grayscale (1 channel) to RGB (3 channels) by repeating
        img = np.repeat(img, 3, axis=0)   # Now shape (3,128,128)
        img = torch.from_numpy(img)
        return img, label

def get_dataloaders(config, task_id):
    if task_id == 0:
        train_ds = StrokeDataset(synthetic=True, length=500)
        val_ds   = StrokeDataset(synthetic=True, length=100)
    elif task_id == 1:
        train_ds = StrokeDataset(synthetic=False, length=int(0.3*500))
        val_ds   = StrokeDataset(synthetic=False, length=100)
    else:
        train_ds = StrokeDataset(synthetic=False, length=500)
        val_ds   = StrokeDataset(synthetic=False, length=100)
    train_loader = DataLoader(train_ds, batch_size=config.batch_size, shuffle=True)
    val_loader   = DataLoader(val_ds,   batch_size=config.batch_size, shuffle=False)
    return train_loader, val_loader

# ------------------------- MODEL -------------------------
class StrokeCNN(nn.Module):
    def __init__(self, num_classes=2, pretrained=True):
        super().__init__()
        self.backbone = models.resnet18(weights='DEFAULT' if pretrained else None)
        in_features = self.backbone.fc.in_features
        self.backbone.fc = nn.Linear(in_features, num_classes)

    def forward(self, x):
        return self.backbone(x)

# ------------------------- REPLAY BUFFER -------------------------
class ReplayBuffer:
    def __init__(self, capacity=200):
        self.capacity = capacity
        self.buffer = deque(maxlen=capacity)

    def push(self, x, y):
        self.buffer.append((x.cpu(), y.cpu()))

    def sample(self, batch_size):
        batch = random.sample(self.buffer, min(len(self.buffer), batch_size))
        x_batch, y_batch = zip(*batch)
        x_batch = torch.stack(x_batch, dim=0)
        y_batch = torch.tensor(y_batch, dtype=torch.long)
        return x_batch, y_batch

    def __len__(self):
        return len(self.buffer)

# ------------------------- EWC -------------------------
class EWC:
    def __init__(self, model, dataloader, device, fisher_sample_size=200):
        self.model = model
        self.device = device
        self.fisher_sample_size = fisher_sample_size
        self.params = {n: p for n, p in model.named_parameters() if p.requires_grad}
        self._means = {}
        self._precision_matrices = {}
        self._compute_fisher(dataloader)

    def _compute_fisher(self, dataloader):
        for n, p in self.params.items():
            self._precision_matrices[n] = torch.zeros_like(p)
            self._means[n] = p.data.clone()

        self.model.eval()
        sample_data = []
        for i, (x, y) in enumerate(dataloader):
            if i * dataloader.batch_size >= self.fisher_sample_size:
                break
            sample_data.append((x, y))

        for x, y in sample_data:
            x, y = x.to(self.device), y.to(self.device)
            self.model.zero_grad()
            output = self.model(x)
            loss = nn.functional.cross_entropy(output, y)
            loss.backward()
            for n, p in self.params.items():
                if p.grad is not None:
                    self._precision_matrices[n] += p.grad.data ** 2 / len(sample_data)

        for n in self.params:
            self._precision_matrices[n] = self._precision_matrices[n].to(self.device)

    def penalty(self, model):
        loss = 0
        for n, p in model.named_parameters():
            if n in self._precision_matrices:
                loss += (self._precision_matrices[n] * (p - self._means[n]) ** 2).sum()
        return loss

# ------------------------- TRAINING FUNCTIONS -------------------------
def evaluate(model, dataloader, config):
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for x, y in dataloader:
            x = x.to(config.device)
            out = model(x)
            pred = out.argmax(dim=1).cpu()
            all_preds.extend(pred.numpy())
            all_labels.extend(y.numpy())
    acc, _ = compute_metrics(all_preds, all_labels)
    return acc

def train_baseline(model, train_loader, val_loader, config, epochs):
    optimizer = torch.optim.Adam(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)
    criterion = nn.CrossEntropyLoss()
    history = {'train_acc': [], 'val_acc': [], 'train_loss': []}
    for epoch in range(epochs):
        model.train()
        running_loss, correct, total = 0.0, 0, 0
        for x, y in tqdm(train_loader, desc=f'Baseline Epoch {epoch+1}'):
            x, y = x.to(config.device), y.to(config.device)
            optimizer.zero_grad()
            out = model(x)
            loss = criterion(out, y)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
            correct += (out.argmax(1) == y).sum().item()
            total += y.size(0)
        train_acc = correct / total
        val_acc = evaluate(model, val_loader, config)
        history['train_acc'].append(train_acc)
        history['val_acc'].append(val_acc)
        history['train_loss'].append(running_loss / len(train_loader))
        print(f"Epoch {epoch+1}: Train Acc {train_acc:.4f}, Val Acc {val_acc:.4f}")
    return history

def train_ewc(model, train_loader, val_loader, config, epochs, ewc, ewc_lambda):
    optimizer = torch.optim.Adam(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)
    criterion = nn.CrossEntropyLoss()
    history = {'train_acc': [], 'val_acc': [], 'train_loss': []}
    for epoch in range(epochs):
        model.train()
        running_loss, correct, total = 0.0, 0, 0
        for x, y in tqdm(train_loader, desc=f'EWC Epoch {epoch+1}'):
            x, y = x.to(config.device), y.to(config.device)
            optimizer.zero_grad()
            out = model(x)
            loss = criterion(out, y) + ewc_lambda * ewc.penalty(model)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
            correct += (out.argmax(1) == y).sum().item()
            total += y.size(0)
        train_acc = correct / total
        val_acc = evaluate(model, val_loader, config)
        history['train_acc'].append(train_acc)
        history['val_acc'].append(val_acc)
        history['train_loss'].append(running_loss / len(train_loader))
        print(f"EWC Epoch {epoch+1}: Train Acc {train_acc:.4f}, Val Acc {val_acc:.4f}")
    return history

def train_replay(model, train_loader, val_loader, config, epochs, buffer):
    optimizer = torch.optim.Adam(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)
    criterion = nn.CrossEntropyLoss()
    history = {'train_acc': [], 'val_acc': [], 'train_loss': []}
    for epoch in range(epochs):
        model.train()
        running_loss, correct, total = 0.0, 0, 0
        for x, y in tqdm(train_loader, desc=f'Replay Epoch {epoch+1}'):
            x, y = x.to(config.device), y.to(config.device)
            optimizer.zero_grad()
            if len(buffer) > 0:
                x_replay, y_replay = buffer.sample(config.replay_batch_size)
                x_replay, y_replay = x_replay.to(config.device), y_replay.to(config.device)
                x = torch.cat([x, x_replay], dim=0)
                y = torch.cat([y, y_replay], dim=0)
            out = model(x)
            loss = criterion(out, y)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
            correct += (out.argmax(1) == y).sum().item()
            total += y.size(0)
            # Store half the batch into buffer
            for xi, yi in zip(x[:x.size(0)//2], y[:y.size(0)//2]):
                buffer.push(xi, yi)
        train_acc = correct / total
        val_acc = evaluate(model, val_loader, config)
        history['train_acc'].append(train_acc)
        history['val_acc'].append(val_acc)
        history['train_loss'].append(running_loss / len(train_loader))
        print(f"Replay Epoch {epoch+1}: Train Acc {train_acc:.4f}, Val Acc {val_acc:.4f}")
    return history

def train_ewc_replay(model, train_loader, val_loader, config, epochs, ewc, buffer, ewc_lambda):
    optimizer = torch.optim.Adam(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)
    criterion = nn.CrossEntropyLoss()
    history = {'train_acc': [], 'val_acc': [], 'train_loss': []}
    for epoch in range(epochs):
        model.train()
        running_loss, correct, total = 0.0, 0, 0
        for x, y in tqdm(train_loader, desc=f'EWC+Replay Epoch {epoch+1}'):
            x, y = x.to(config.device), y.to(config.device)
            optimizer.zero_grad()
            if len(buffer) > 0:
                x_replay, y_replay = buffer.sample(config.replay_batch_size)
                x_replay, y_replay = x_replay.to(config.device), y_replay.to(config.device)
                x = torch.cat([x, x_replay], dim=0)
                y = torch.cat([y, y_replay], dim=0)
            out = model(x)
            loss = criterion(out, y) + ewc_lambda * ewc.penalty(model)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
            correct += (out.argmax(1) == y).sum().item()
            total += y.size(0)
            for xi, yi in zip(x[:x.size(0)//2], y[:y.size(0)//2]):
                buffer.push(xi, yi)
        train_acc = correct / total
        val_acc = evaluate(model, val_loader, config)
        history['train_acc'].append(train_acc)
        history['val_acc'].append(val_acc)
        history['train_loss'].append(running_loss / len(train_loader))
        print(f"EWC+Replay Epoch {epoch+1}: Train Acc {train_acc:.4f}, Val Acc {val_acc:.4f}")
    return history

# ------------------------- FISHER HEATMAP (NEW) -------------------------
def plot_fisher_heatmap(model, dataloader, config, save_path="./plots/fisher_heatmap.png"):
    """
    Compute Fisher Information for the first convolutional layer and plot a bar chart.
    This shows which filters are most important for the learned tasks.
    """
    # Create EWC object on the trained model (this computes Fisher diagonals)
    ewc = EWC(model, dataloader, config.device, fisher_sample_size=100)

    # Get Fisher diagonal for the first conv layer (backbone.conv1.weight)
    first_conv_name = 'backbone.conv1.weight'
    if first_conv_name not in ewc._precision_matrices:
        print(f"Could not find {first_conv_name} in Fisher matrices. Available layers:")
        print(list(ewc._precision_matrices.keys())[:5])  # show first 5
        return

    fisher_values = ewc._precision_matrices[first_conv_name].detach().cpu().numpy()
    # fisher_values shape: [out_channels, in_channels, kernel_h, kernel_w] = [64, 3, 7, 7]
    # Mean over in_channels and spatial dimensions to get one value per filter
    mean_fisher_per_filter = fisher_values.mean(axis=(1, 2, 3))

    # Create the plot
    plt.figure(figsize=(12, 5))
    plt.bar(range(len(mean_fisher_per_filter)), mean_fisher_per_filter, color='steelblue')
    plt.xlabel('Filter Index (first convolutional layer)', fontsize=12)
    plt.ylabel('Mean Fisher Information', fontsize=12)
    plt.title('Fisher Information per Conv Filter – EWC identifies critical features', fontsize=14)
    plt.grid(axis='y', linestyle='--', alpha=0.7)

    # Optional: add a horizontal line at mean value
    mean_val = mean_fisher_per_filter.mean()
    plt.axhline(y=mean_val, color='red', linestyle='--', label=f'Mean = {mean_val:.4f}')
    plt.legend()

    # Save the figure
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Fisher Information heatmap saved to {save_path}")

# ------------------------- MAIN EXPERIMENT LOOP -------------------------
def run_incremental_experiment(config, strategy_name):
    model = StrokeCNN(num_classes=config.num_classes).to(config.device)
    set_seed(config.seed)
    buffer = ReplayBuffer(config.buffer_capacity) if 'replay' in strategy_name else None
    all_val_accs = []
    for task_id in range(3):
        print(f"\n--- Task {task_id+1} ---")
        train_loader, val_loader = get_dataloaders(config, task_id)
        ewc = None
        if strategy_name != 'baseline' and task_id > 0:
            ewc = EWC(model, train_loader, config.device, config.fisher_sample_size)
        epochs = config.epochs_per_task
        if strategy_name == 'baseline':
            history = train_baseline(model, train_loader, val_loader, config, epochs)
        elif strategy_name == 'ewc':
            if task_id == 0:
                history = train_baseline(model, train_loader, val_loader, config, epochs)
            else:
                history = train_ewc(model, train_loader, val_loader, config, epochs, ewc, config.ewc_lambda)
        elif strategy_name == 'replay':
            if task_id == 0:
                history = train_baseline(model, train_loader, val_loader, config, epochs)
            else:
                history = train_replay(model, train_loader, val_loader, config, epochs, buffer)
        elif strategy_name == 'ewc_replay':
            if task_id == 0:
                history = train_baseline(model, train_loader, val_loader, config, epochs)
            else:
                history = train_ewc_replay(model, train_loader, val_loader, config, epochs, ewc, buffer, config.ewc_lambda)
        else:
            raise ValueError(f"Unknown strategy: {strategy_name}")
        # Evaluate on all three tasks so far
        accs_on_all = []
        for tid in range(3):
            _, val_loader_tid = get_dataloaders(config, tid)
            acc = evaluate(model, val_loader_tid, config)
            accs_on_all.append(acc)
        all_val_accs.append(accs_on_all)
        print(f"After Task {task_id+1}: Accuracies on Task0,1,2 = {accs_on_all}")
        os.makedirs(config.model_dir, exist_ok=True)
        save_checkpoint(model, None, task_id, os.path.join(config.model_dir, f"{strategy_name}_task{task_id}.pt"))
    return all_val_accs

def main():
    config = Config()
    os.makedirs(config.plot_dir, exist_ok=True)
    strategies = ['baseline', 'ewc', 'replay', 'ewc_replay']
    results = {}
    for strat in strategies:
        print(f"\n========== Running {strat.upper()} ==========")
        results[strat] = run_incremental_experiment(config, strat)

    # Save raw results
    with open(os.path.join(config.plot_dir, 'results.pkl'), 'wb') as f:
        pickle.dump(results, f)

    # -------------------- FISHER HEATMAP (NEW) --------------------
    print("\n--- Generating Fisher Information Heatmap ---")
    best_strategy = 'ewc_replay'
    checkpoint_path = os.path.join(config.model_dir, f"{best_strategy}_task2.pt")

    if os.path.exists(checkpoint_path):
        model = StrokeCNN(num_classes=config.num_classes).to(config.device)
        checkpoint = torch.load(checkpoint_path, map_location=config.device)
        model.load_state_dict(checkpoint['model_state_dict'])
        print(f"Loaded {best_strategy} model from {checkpoint_path}")

        _, val_loader = get_dataloaders(config, task_id=2)
        plot_fisher_heatmap(model, val_loader, config, save_path=os.path.join(config.plot_dir, "fisher_heatmap.png"))
    else:
        print(f"Checkpoint {checkpoint_path} not found. Fisher heatmap skipped.")
    # -------------------------------------------------------------

    # Plot average accuracy (existing)
    plt.figure(figsize=(10,6))
    for strat, acc_hist in results.items():
        avg_accs = [np.mean(acc_hist[i][:i+1]) for i in range(len(acc_hist))]
        plt.plot(range(1, len(avg_accs)+1), avg_accs, marker='o', label=strat)
    plt.xlabel('Task Number')
    plt.ylabel('Average Accuracy on Seen Tasks')
    plt.title('Continual Learning Performance')
    plt.legend()
    plt.grid(True)
    plt.savefig(os.path.join(config.plot_dir, 'avg_accuracy.png'), dpi=150)
    plt.close()

    # Plot backward transfer (existing)
    strategies_list = ['baseline', 'ewc', 'replay', 'ewc_replay']
    bwt_values = []
    for strat in strategies_list:
        acc0_after_task0 = results[strat][0][0]
        acc0_after_task2 = results[strat][2][0]
        bwt_values.append(acc0_after_task2 - acc0_after_task0)
    plt.figure(figsize=(8,5))
    sns.barplot(x=strategies_list, y=bwt_values)
    plt.axhline(y=0, color='r', linestyle='--')
    plt.ylabel('Backward Transfer (BWT)')
    plt.title('Forgetting: Change in Task 0 Accuracy after Learning Task 2')
    plt.savefig(os.path.join(config.plot_dir, 'backward_transfer.png'), dpi=150)
    plt.close()

    print(f"All plots saved to {config.plot_dir}")

if __name__ == "__main__":
    main()

import matplotlib.pyplot as plt
import os

fisher_path = "./plots/fisher_heatmap.png"
if os.path.exists(fisher_path):
    img = plt.imread(fisher_path)
    plt.figure(figsize=(12, 5))
    plt.imshow(img)
    plt.axis('off')
    plt.title("Fisher Information Heatmap (First Conv Layer)", fontsize=14)
    plt.show()
else:
    print("Fisher heatmap not found. Run the experiment first.")

import os
print(os.getcwd())

!ls ./plots

from IPython.display import Image
Image(filename='./plots/avg_accuracy.png')

from IPython.display import Image
Image(filename='./plots/backward_transfer.png')