# -*- coding: utf-8 -*-
"""Continuous Learning Ischemic Stroke Assessment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGKYB-ps9tqL0bpTpUn_jQx5B6wdr0Dk
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# torch>=2.0.0
# torchvision>=0.15.0
# numpy>=1.24.0
# matplotlib>=3.7.0
# seaborn>=0.12.0
# tqdm>=4.65.0
# scikit-learn>=1.3.0
# pandas>=2.0.0
# pillow>=9.5.0
# kagglehub>=0.2.0
# nibabel>=5.0.0
# requests>=2.28.0

pip install -r requirements.txt

import os
import random
import pickle
import numpy as np
import torch
import torch.nn as nn
import torchvision.models as models
from torch.utils.data import Dataset, DataLoader, ConcatDataset
from PIL import Image
from tqdm import tqdm
from collections import deque
from sklearn.metrics import accuracy_score, f1_score
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
import requests
import zipfile
import glob
import nibabel as nib

# ------------------------- CONFIG -------------------------
class Config:
    img_size = (128, 128)
    num_classes = 2
    batch_size = 32
    epochs_per_task = 5
    lr = 1e-3
    weight_decay = 1e-4
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    seed = 42
    ewc_lambda = 5000
    fisher_sample_size = 200
    buffer_capacity = 200
    replay_batch_size = 32
    plot_dir = "./plots_corrected_v2"
    model_dir = "./checkpoints_corrected_v2"
    data_dir = "./data"

    strategies = ['baseline', 'ewc', 'replay', 'ewc_replay']
    strategy_labels = {
        'baseline': 'Baseline',
        'ewc': 'EWC Only',
        'replay': 'Replay Only',
        'ewc_replay': 'EWC + Replay',
    }
    strategy_colors = {
        'baseline': '#e74c3c',
        'ewc': '#f39c12',
        'replay': '#3498db',
        'ewc_replay': '#2ecc71',
    }

# ------------------------- UTILS -------------------------
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def compute_metrics(preds, labels):
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average='binary', zero_division=0)
    return acc, f1

def save_checkpoint(model, optimizer, epoch, filename):
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict() if optimizer else None,
    }, filename)

# ------------------------- DATASET 1: Brain Stroke CT (Kaggle) -------------------------
class StrokeCTDataset(Dataset):
    def __init__(self, split='train', img_size=(128, 128)):
        self.img_size = img_size
        self.split = split
        self.data_dir = self._get_dataset_path()
        self.image_paths, self.labels = self._load_dataset()
        print(f"[CT] {split}: {len(self.image_paths)} images (Stroke: {self.labels.count(1)}, Normal: {self.labels.count(0)})")

    def _get_dataset_path(self):
        if os.path.exists("/kaggle/input/brain-stroke-ct-image-dataset"):
            return "/kaggle/input/brain-stroke-ct-image-dataset"
        os.makedirs(Config.data_dir, exist_ok=True)
        extract_path = os.path.join(Config.data_dir, "brain_stroke_ct")
        if os.path.exists(extract_path) and len(os.listdir(extract_path)) > 0:
            return extract_path
        print("Downloading Brain Stroke CT dataset from Kaggle...")
        try:
            path = kagglehub.dataset_download("afridirahman/brain-stroke-ct-image-dataset")
        except Exception as e:
            raise RuntimeError(f"Failed to download CT dataset: {e}")
        zip_files = glob.glob(os.path.join(path, "*.zip"))
        if zip_files:
            with zipfile.ZipFile(zip_files[0], 'r') as zip_ref:
                zip_ref.extractall(extract_path)
            return extract_path
        return path

    def _label_from_path(self, path):
        p = path.lower()
        # Check for Brain_Data_Organised structure
        if "brain_data_organised" in p:
            if "normal" in p:
                return 0
            if "stroke" in p:
                return 1
        # Fallback: check filename
        if "normal" in p:
            return 0
        if "stroke" in p:
            return 1
        return None

    def _load_dataset(self):
        if not os.path.exists(self.data_dir):
            raise FileNotFoundError(f"CT dataset not found at {self.data_dir}.")

        image_paths, labels = [], []
        valid_ext = ('.jpg', '.jpeg', '.png')

        for root, _, files in os.walk(self.data_dir):
            for f in files:
                if not f.lower().endswith(valid_ext):
                    continue
                full_path = os.path.join(root, f)
                label = self._label_from_path(full_path)
                if label is None:
                    continue
                image_paths.append(full_path)
                labels.append(label)

        if len(image_paths) == 0:
            raise FileNotFoundError(f"No labeled images found in {self.data_dir}.")

        indices = list(range(len(image_paths)))
        np.random.seed(42)
        np.random.shuffle(indices)
        split_idx = int(0.8 * len(indices))
        indices = indices[:split_idx] if self.split == 'train' else indices[split_idx:]
        return [image_paths[i] for i in indices], [labels[i] for i in indices]

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        label = self.labels[idx]
        try:
            img = Image.open(img_path).convert('L')
            img = img.resize(self.img_size, Image.Resampling.LANCZOS)
            img = np.array(img, dtype=np.float32) / 255.0
            img = np.repeat(img[np.newaxis, :, :], 3, axis=0)
            img = torch.from_numpy(img)
        except Exception as e:
            print(f"Error loading {img_path}: {e}")
            img = torch.zeros(3, *self.img_size, dtype=torch.float32)
        return img, torch.tensor(label, dtype=torch.long)

# ------------------------- DATASET 2: ISLES 2022 (MRI) - REAL LABELS -------------------------
class ISLES2022Dataset(Dataset):
    """ISLES-2022 with REAL labels from lesion masks."""
    def __init__(self, split='train', img_size=(128, 128)):
        self.img_size = img_size
        self.split = split
        self.data_dir = os.path.join(Config.data_dir, "isles2022")
        self._download_dataset()
        self.image_paths, self.labels = self._load_dataset()
        print(f"[ISLES] {split}: {len(self.image_paths)} volumes (Lesion: {self.labels.count(1)}, No Lesion: {self.labels.count(0)})")

    def _download_dataset(self):
        marker = os.path.join(self.data_dir, ".download_complete")
        if os.path.exists(marker):
            return
        os.makedirs(self.data_dir, exist_ok=True)
        url = "https://zenodo.org/records/7960856/files/ISLES-2022.zip"
        print("Downloading ISLES-2022 (this may take ~10 min)...")
        zip_path = os.path.join(self.data_dir, "ISLES-2022.zip")
        try:
            response = requests.get(url, stream=True)
            response.raise_for_status()
            total_size = int(response.headers.get('content-length', 0))
            with open(zip_path, 'wb') as f:
                with tqdm(total=total_size, unit='B', unit_scale=True, desc="ISLES-2022") as pbar:
                    for chunk in response.iter_content(chunk_size=1024*1024):
                        f.write(chunk)
                        pbar.update(len(chunk))
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(self.data_dir)
            os.remove(zip_path)
            with open(marker, 'w') as f:
                f.write("ok")
        except Exception as e:
            raise RuntimeError(f"Failed to download ISLES-2022: {e}")

    def _load_dataset(self):
        """Find raw volumes and their corresponding lesion masks. Label = 1 if lesion exists."""
        if not os.path.exists(self.data_dir):
            raise FileNotFoundError(f"ISLES-2022 not found at {self.data_dir}.")

        raw_paths, mask_paths = [], []
        for root, _, files in os.walk(self.data_dir):
            # Skip derivatives folder (contains masks)
            if "derivatives" in root:
                continue
            for f in files:
                if f.lower().endswith(('.nii.gz', '.nii')):
                    full_path = os.path.join(root, f)
                    raw_paths.append(full_path)

        # Find corresponding masks
        mask_dir = os.path.join(self.data_dir, "derivatives")
        if os.path.exists(mask_dir):
            for root, _, files in os.walk(mask_dir):
                for f in files:
                    if f.lower().endswith(('.nii.gz', '.nii')):
                        mask_paths.append(os.path.join(root, f))

        print(f"Found {len(raw_paths)} raw volumes, {len(mask_paths)} masks")

        # Match raw volumes to masks by subject ID
        raw_by_subject = {}
        for r in raw_paths:
            subj = os.path.basename(os.path.dirname(r))
            raw_by_subject.setdefault(subj, []).append(r)

        mask_by_subject = {}
        for m in mask_paths:
            # Extract subject ID from mask path
            parts = m.split(os.sep)
            for p in parts:
                if p.startswith("sub-"):
                    subj = p
                    break
            mask_by_subject.setdefault(subj, []).append(m)

        samples = []
        for subj in raw_by_subject:
            raw_vols = raw_by_subject[subj]
            masks = mask_by_subject.get(subj, [])
            if masks:
                # Use first mask (DWI lesion mask)
                mask_path = masks[0]
            else:
                mask_path = None
            for rv in raw_vols:
                samples.append((rv, mask_path))

        if len(samples) == 0:
            raise FileNotFoundError(f"No samples found in {self.data_dir}.")

        # Load labels from masks
        image_paths, labels = [], []
        for raw_path, mask_path in samples:
            image_paths.append(raw_path)
            if mask_path is None:
                labels.append(0)
            else:
                try:
                    mask_data = nib.load(mask_path).get_fdata()
                    labels.append(1 if np.any(mask_data > 0) else 0)
                except Exception as e:
                    print(f"Warning: Could not read mask {mask_path}: {e}")
                    labels.append(0)

        # Split
        indices = list(range(len(image_paths)))
        np.random.seed(42)
        np.random.shuffle(indices)
        split_idx = int(0.8 * len(indices))
        indices = indices[:split_idx] if self.split == 'train' else indices[split_idx:]
        return [image_paths[i] for i in indices], [labels[i] for i in indices]

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        nii_path = self.image_paths[idx]
        label = self.labels[idx]
        try:
            vol = nib.load(nii_path).get_fdata(dtype=np.float32)
            mid = vol.shape[2] // 2
            slice_2d = vol[:, :, mid]
            lo, hi = np.percentile(slice_2d, 1), np.percentile(slice_2d, 99)
            if hi - lo < 1e-6:
                hi = slice_2d.max() if slice_2d.max() > 0 else 1.0
                lo = 0.0
            slice_2d = np.clip((slice_2d - lo) / (hi - lo + 1e-8), 0, 1)
            img = Image.fromarray((slice_2d * 255).astype(np.uint8))
            img = img.resize(self.img_size, Image.Resampling.LANCZOS)
            arr = np.array(img, dtype=np.float32) / 255.0
            arr = np.repeat(arr[np.newaxis, :, :], 3, axis=0)
            img = torch.from_numpy(arr)
        except Exception as e:
            print(f"Error loading {nii_path}: {e}")
            img = torch.zeros(3, *self.img_size, dtype=torch.float32)
        return img, torch.tensor(label, dtype=torch.long)

# ------------------------- DATALOADER -------------------------
def get_dataloaders(config, task_id, split='train'):
    if task_id == 0:
        # Task 1: CT only
        if split == 'train':
            ds = StrokeCTDataset(split='train', img_size=config.img_size)
        else:
            ds = StrokeCTDataset(split='val', img_size=config.img_size)
    else:
        # Task 2: CT + ISLES-2022
        if split == 'train':
            ds = ConcatDataset([
                StrokeCTDataset(split='train', img_size=config.img_size),
                ISLES2022Dataset(split='train', img_size=config.img_size)
            ])
        else:
            ds = ConcatDataset([
                StrokeCTDataset(split='val', img_size=config.img_size),
                ISLES2022Dataset(split='val', img_size=config.img_size)
            ])
    return DataLoader(ds, batch_size=config.batch_size, shuffle=(split=='train'))

# ------------------------- MODEL -------------------------
class StrokeCNN(nn.Module):
    def __init__(self, num_classes=2, pretrained=True):
        super().__init__()
        self.backbone = models.resnet18(weights='DEFAULT' if pretrained else None)
        in_features = self.backbone.fc.in_features
        self.backbone.fc = nn.Linear(in_features, num_classes)

    def forward(self, x):
        return self.backbone(x)

# ------------------------- REPLAY BUFFER -------------------------
class ReplayBuffer:
    def __init__(self, capacity=200):
        self.capacity = capacity
        self.buffer = deque(maxlen=capacity)

    def push(self, x, y):
        self.buffer.append((x.detach().cpu(), y.detach().cpu()))

    def sample(self, batch_size):
        if len(self.buffer) == 0:
            return None, None
        batch = random.sample(self.buffer, min(len(self.buffer), batch_size))
        x_batch, y_batch = zip(*batch)
        return torch.stack(x_batch, dim=0), torch.tensor(y_batch, dtype=torch.long)

    def __len__(self):
        return len(self.buffer)

# ------------------------- EWC -------------------------
class EWC:
    def __init__(self, model, dataloader, device, fisher_sample_size=200):
        self.model = model
        self.device = device
        self.fisher_sample_size = fisher_sample_size
        self.params = {n: p for n, p in model.named_parameters() if p.requires_grad}
        self._means = {}
        self._precision_matrices = {}
        self._compute_fisher(dataloader)

    def _compute_fisher(self, dataloader):
        for n, p in self.params.items():
            self._precision_matrices[n] = torch.zeros_like(p)
            self._means[n] = p.data.clone()

        self.model.eval()
        n_batches = 0
        samples_seen = 0
        for x, y in dataloader:
            if samples_seen >= self.fisher_sample_size:
                break
            x, y = x.to(self.device), y.to(self.device)
            self.model.zero_grad()
            output = self.model(x)
            loss = nn.functional.cross_entropy(output, y)
            loss.backward()
            for n, p in self.params.items():
                if p.grad is not None:
                    self._precision_matrices[n] += p.grad.data ** 2
            n_batches += 1
            samples_seen += x.size(0)

        for n in self._precision_matrices:
            if n_batches > 0:
                self._precision_matrices[n] /= n_batches

    def penalty(self, model):
        loss = 0.0
        for n, p in model.named_parameters():
            if n in self._precision_matrices:
                loss += (self._precision_matrices[n] * (p - self._means[n]) ** 2).sum()
        return loss

# ------------------------- TRAINING -------------------------
def train_epoch(model, train_loader, val_loader, config, epochs, tag, ewc=None, buffer=None):
    optimizer = torch.optim.Adam(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        model.train()
        running_loss, correct, total = 0.0, 0, 0

        for x, y in tqdm(train_loader, desc=f'{tag} Epoch {epoch+1}'):
            x, y = x.to(config.device), y.to(config.device)

            # --- Replay buffer: sample old examples ---
            x_replay, y_replay = None, None  # Initialize to avoid UnboundLocalError
            if buffer is not None and len(buffer) > 0:
                x_replay, y_replay = buffer.sample(config.replay_batch_size)
                if x_replay is not None:
                    x_replay = x_replay.to(config.device)
                    y_replay = y_replay.to(config.device)
                    x = torch.cat([x, x_replay], dim=0)
                    y = torch.cat([y, y_replay], dim=0)

            optimizer.zero_grad()
            out = model(x)
            loss = criterion(out, y)

            # EWC penalty
            if ewc is not None:
                loss += config.ewc_lambda * ewc.penalty(model)

            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            correct += (out.argmax(1) == y).sum().item()
            total += y.size(0)

            # --- Store samples in replay buffer ---
            if buffer is not None:
                # Determine how many original (non-replay) samples were in the batch
                if x_replay is not None and y_replay is not None:
                    orig_len = len(y) - len(y_replay)
                else:
                    orig_len = len(y)
                for i in range(orig_len):
                    buffer.push(x[i], y[i])

        train_acc = correct / total
        val_acc, _ = evaluate(model, val_loader, config)
        print(f"  {tag} Epoch {epoch+1}: train_acc={train_acc:.4f}, val_acc={val_acc:.4f}")

def evaluate(model, dataloader, config):
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for x, y in dataloader:
            x = x.to(config.device)
            out = model(x)
            pred = out.argmax(dim=1).cpu()
            all_preds.extend(pred.numpy())
            all_labels.extend(y.numpy())
    acc, f1 = compute_metrics(all_preds, all_labels)
    return acc, f1

# ------------------------- RUN EXPERIMENT -------------------------
def run_experiment(config, strategy):
    set_seed(config.seed)
    model = StrokeCNN(num_classes=config.num_classes).to(config.device)
    buffer = ReplayBuffer(config.buffer_capacity) if 'replay' in strategy else None

    all_accs = []

    for task_id in range(2):
        print(f"\n--- Strategy: {strategy} | Task {task_id+1} ---")

        train_loader = get_dataloaders(config, task_id, split='train')
        val_loader = get_dataloaders(config, task_id, split='val')

        ewc = None
        if ('ewc' in strategy) and task_id == 1:
            task0_loader = get_dataloaders(config, 0, split='train')
            ewc = EWC(model, task0_loader, config.device, config.fisher_sample_size)
            print(f"EWC penalty lambda: {config.ewc_lambda}")

        train_epoch(model, train_loader, val_loader, config, config.epochs_per_task,
                    tag=f"{strategy}/T{task_id+1}", ewc=ewc, buffer=buffer)

        # Evaluate on both tasks
        accs = []
        for tid in range(2):
            # FIXED: correct function name and no unpacking (returns one DataLoader)
            val_loader_tid = get_dataloaders(config, tid, split='val')
            # evaluate returns (acc, f1) – take the first value
            acc = evaluate(model, val_loader_tid, config)[0]
            accs.append(acc)
        all_accs.append(accs)
        print(f"  After Task {task_id+1}: Accuracy on Task0={accs[0]:.4f}, Task1={accs[1]:.4f}")

        save_checkpoint(model, None, task_id,
                        os.path.join(config.model_dir, f"{strategy}_task{task_id}.pt"))

    return all_accs

# ------------------------- PLOTTING -------------------------
def plot_results(config, results):
    os.makedirs(config.plot_dir, exist_ok=True)

    # Average Accuracy
    plt.figure(figsize=(10, 6))
    for strat in config.strategies:
        accs = results[strat]
        avg_accs = [np.mean(accs[i][:i+1]) for i in range(len(accs))]
        plt.plot(range(1, len(avg_accs)+1), avg_accs, marker='o', linewidth=2.5,
                 label=config.strategy_labels[strat], color=config.strategy_colors[strat])
        for i, v in enumerate(avg_accs):
            plt.text(i+1, v+0.01, f'{v:.2f}', ha='center', va='bottom', fontsize=9)

    plt.xlabel('Task Number')
    plt.ylabel('Average Accuracy on Seen Tasks')
    plt.title('Continual Learning Performance (2 Real Datasets)')
    plt.xticks([1, 2], ['Task 1 (CT only)', 'Task 2 (+ ISLES-2022)'])
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(config.plot_dir, 'avg_accuracy.png'), dpi=200)
    plt.close()
    print(f"Saved: avg_accuracy.png")

    # Backward Transfer
    bwt_values = []
    for strat in config.strategies:
        acc_task0_after_task0 = results[strat][0][0]
        acc_task0_after_task1 = results[strat][1][0]
        bwt = acc_task0_after_task1 - acc_task0_after_task0
        bwt_values.append(bwt)

    plt.figure(figsize=(9, 6))
    labels = [config.strategy_labels[s] for s in config.strategies]
    colors = [config.strategy_colors[s] for s in config.strategies]
    bars = plt.bar(labels, bwt_values, color=colors, edgecolor='black')
    plt.axhline(y=0, color='red', linestyle='--', linewidth=2, label='No Forgetting')

    for bar, val in zip(bars, bwt_values):
        y_pos = val + 0.005 if val >= 0 else val - 0.015
        va = 'bottom' if val >= 0 else 'top'
        color = 'green' if val > 0 else 'red'
        plt.text(bar.get_x() + bar.get_width()/2, y_pos, f'{val:.3f}',
                 ha='center', va=va, fontsize=12, fontweight='bold', color=color)

    plt.ylabel('Backward Transfer (BWT)')
    plt.xlabel('Strategy')
    plt.title('Forgetting Measure (BWT) – Real Results')
    plt.legend()
    plt.grid(alpha=0.3, axis='y')
    plt.tight_layout()
    plt.savefig(os.path.join(config.plot_dir, 'backward_transfer.png'), dpi=200)
    plt.close()
    print(f"Saved: backward_transfer.png")

    print("\n📈 KEY RESULTS:")
    for strat, bwt in zip(config.strategies, bwt_values):
        print(f"  {config.strategy_labels[strat]:<15} BWT = {bwt:+.3f}")

    return bwt_values

# ------------------------- MAIN -------------------------
def main():
    config = Config()
    os.makedirs(config.plot_dir, exist_ok=True)
    os.makedirs(config.model_dir, exist_ok=True)

    print("="*70)
    print("Continual Learning with Real Datasets")
    print("Brain Stroke CT (Kaggle) + ISLES-2022 (Zenodo)")
    print("="*70)

    results = {}
    for strat in config.strategies:
        print(f"\n{'='*20} {strat.upper()} {'='*20}")
        results[strat] = run_experiment(config, strat)

    with open(os.path.join(config.plot_dir, 'results.pkl'), 'wb') as f:
        pickle.dump(results, f)

    bwt_values = plot_results(config, results)

    print("\n" + "="*70)
    print("✅ DONE!")
    print(f"Plots saved in: {config.plot_dir}")
    print("="*70)

if __name__ == "__main__":
    main()

import os
from google.colab import files

# Folder where plots and checkpoints are saved
plot_dir = "./plots_corrected_v2"
checkpoint_dir = "./checkpoints_corrected_v2"

# List all files you want to download (you can add or remove)
files_to_download = [
    os.path.join(plot_dir, "avg_accuracy.png"),
    os.path.join(plot_dir, "backward_transfer.png"),
    os.path.join(plot_dir, "fisher_heatmap.png"),
    os.path.join(plot_dir, "results.pkl"),
]

# Add checkpoint files if they exist
strategies = ['baseline', 'ewc', 'replay', 'ewc_replay']
for strat in strategies:
    for task in range(2):
        ckpt = os.path.join(checkpoint_dir, f"{strat}_task{task}.pt")
        if os.path.exists(ckpt):
            files_to_download.append(ckpt)

# Download only existing files
downloaded = 0
missing = []

for file_path in files_to_download:
    if os.path.exists(file_path):
        try:
            files.download(file_path)
            print(f"✅ Downloaded: {os.path.basename(file_path)}")
            downloaded += 1
        except Exception as e:
            print(f"❌ Failed to download {os.path.basename(file_path)}: {e}")
    else:
        missing.append(file_path)

print(f"\n✅ Downloaded {downloaded} files.")
if missing:
    print("⚠️ The following files were not found and were skipped:")
    for m in missing:
        print(f"   - {m}")

import os
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. Load the ewc_replay checkpoint ---
checkpoint_path = "./checkpoints_corrected_v2/ewc_replay_task1.pt"

if not os.path.exists(checkpoint_path):
    print(f"❌ Checkpoint not found: {checkpoint_path}")
else:
    print("✅ Checkpoint found. Loading model...")

    # --- 2. Load the model ---
    model = StrokeCNN(num_classes=2).to(Config.device)
    checkpoint = torch.load(checkpoint_path, map_location=Config.device)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()
    print("✅ Model loaded successfully.")

    # --- 3. Get validation loader (Task 1: CT + ISLES) ---
    # FIX: get_dataloaders returns a single DataLoader, not a tuple
    val_loader = get_dataloaders(Config, 1, split='val')
    print("✅ Validation dataloader ready.")

    # --- 4. Compute Fisher Information for Conv1 layer ---
    print("🔄 Computing Fisher Information...")
    ewc = EWC(model, val_loader, Config.device, fisher_sample_size=100)

    first_conv_name = 'backbone.conv1.weight'
    if first_conv_name not in ewc._precision_matrices:
        print(f"❌ Could not find {first_conv_name} in Fisher matrices.")
    else:
        fisher_values = ewc._precision_matrices[first_conv_name].detach().cpu().numpy()
        per_filter = fisher_values.mean(axis=(1, 2, 3))

        # --- 5. Save bar chart ---
        print("🔄 Generating bar chart...")
        plt.figure(figsize=(12, 5))
        plt.bar(range(len(per_filter)), per_filter, color='steelblue', edgecolor='navy', alpha=0.8)
        plt.xlabel('Filter Index (First Convolutional Layer)', fontsize=13)
        plt.ylabel('Mean Fisher Information', fontsize=13)
        plt.title('Fisher Information per Conv Filter – EWC identifies critical features', fontsize=14, fontweight='bold')
        plt.grid(axis='y', linestyle='--', alpha=0.4)
        mean_val = per_filter.mean()
        plt.axhline(y=mean_val, color='red', linestyle='--', linewidth=2, label=f'Mean = {mean_val:.6f}')
        plt.legend(fontsize=11)
        plt.tight_layout()
        bar_path = "./plots_corrected_v2/fisher_heatmap.png"
        os.makedirs(os.path.dirname(bar_path), exist_ok=True)
        plt.savefig(bar_path, dpi=200, bbox_inches='tight')
        plt.close()
        print(f"✅ Fisher bar chart saved to: {bar_path}")

        # --- 6. Save grid heatmap (8x8) ---
        print("🔄 Generating grid heatmap...")
        grid = per_filter.reshape(8, 8)
        plt.figure(figsize=(8, 7))
        sns.heatmap(grid, cmap='rocket', annot=True, fmt='.5f',
                    cbar_kws={'label': 'Mean Fisher Information'})
        plt.title('Fisher Information Heatmap (Conv1, 8x8 grid)', fontsize=14, fontweight='bold')
        plt.xlabel('Filter Column')
        plt.ylabel('Filter Row')
        plt.tight_layout()
        grid_path = "./plots_corrected_v2/fisher_heatmap_grid.png"
        plt.savefig(grid_path, dpi=200, bbox_inches='tight')
        plt.close()
        print(f"✅ Fisher grid heatmap saved to: {grid_path}")

        # --- 7. Download (Colab) ---
        try:
            from google.colab import files
            files.download(bar_path)
            print("📥 Downloaded: fisher_heatmap.png")
            files.download(grid_path)
            print("📥 Downloaded: fisher_heatmap_grid.png")
        except ImportError:
            print("ℹ️ Not in Colab – files are saved locally in ./plots_corrected_v2/")

